routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('CryptOne', 'CryptOneController');
Route::post('crypt','CryptOneController@crypt')->name("CryptOne.crypt");
Route::resource('CryptTwo', 'CryptTwoController');
Route::post('crypt_two','CryptTwoController@crypt')->name("CryptTwo.crypt");
Route::get('crypt_tree','CryptTreeController@index')->name("CryptTree.crypt");
Route::post('crypt_tree_crypt','CryptTreeController@crypt')->name("CryptTree.crypt.go");
Route::get('crypt_tree_ru','CryptTreeControllerRu@index')->name("CryptTree.crypt.ru");
Route::post('crypt_tree_crypt_rus','CryptTreeControllerRu@crypt')->name("CryptTree.crypt.rus");
Route::get('vernam','CryptTreeController@ver_index')->name("CryptTree.Vernam");
Route::post('vernam_crypt','CryptTreeController@ver_crypt')->name("CryptTree.Vernam.ver_crypt");
Route::get('crypt_five','CryptFiveController@index')->name("CryptFive");
Route::post('crypt_five_crypting','CryptFiveController@crypting')->name("CryptFive.crypting");
Route::get('rsa','RSAController@index')->name("rsa");
Route::post('rsa_crypting','RSAController@RSA')->name("RSA.crypting");
Route::get('aes','AESController@index')->name("aes");
Route::post('aes_crypting','AESController@AES')->name("AES.crypting");

resources/views/AES.blade.php
@extends('layouts.app')

@section('content')
    @include('include.errors')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif


                        <form class="form-horizontal" action="{{route('AES.crypting')}}" method="post">
                            {{csrf_field()}}
                            {{ method_field('POST') }}
                            {{--form include--}}
                            <div class="container">

                                <div class="row">
                                    <div class="col-sm">
                                        <label for="">Сообщение</label>
                                        <input class="form-control" type="text" placeholder="text"
                                               name="mess">
                                    </div>
                                    <div class="col-sm">
                                        <label for="">Ключ</label>
                                        <input class="form-control" type="text" name="key"
                                               placeholder="exaple@mail.ru">
                                    </div>
                                </div>
                                <hr/>

                                <hr/>

                                <div class="row myrow">

                                    <div class="col-sm pb-2" style="display: grid">
                                        <input class="btn btn-primary" name="action" type="submit" value="зашифровать">

                                    </div>


                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="container">
                        @if(isset($messages) and isset($keys))
                            <div class="alert alert-primary" role="alert">
                                Сообщение: {{$messages}} <br>
                                Ключ: {{$keys}}
                            </div>

                            <div class="alert alert-danger" role="alert">
                                 -L EFT  : {{implode($arrL)}}<br>
                                RIGHT : {{implode($arrR)}}<br>
                                After {{$n}} Rounds encr message is :<br>
                                {{implode($crypt)}} <br>

                            </div>
                            <div class="alert alert-success" role="alert">
                                Расшифрованное сообщение по ключу : {{implode($crypt)}} <br>

                                Будет : {{$decord}}
                            </div>

                        @endif
                    </div>

                </div>


                <div class="container">
                    @if(isset($test))
                    <div class="alert alert-success" role="alert">
                        Демонстрационный массив
                    </div>

                    <table class="table table-bordered table-hover">

                        <tbody>

                        @forelse($test as  $te => $t)
                            <tr>
                                @foreach($t as $tt)
                                    <td>{{$tt}}</td>
                                @endforeach
                            </tr>
                        @empty
                            <tr>
                                <td colspan="9" class="text-center"><h2>Данные отстутсвуют</h2></td>
                            </tr>
                        @endforelse
                        </tbody>

                    </table>
                    @endif
                        @if(isset($decode))
                            <div class="alert alert-info" role="alert">
                                A simple info alert—check it out!
                            </div>

                            <table class="table table-bordered table-hover">

                                <tbody>

                                @forelse($decode as $dec => $t)
                                    <tr>
                                        @foreach($t as $tt)
                                            <td>{{$tt}}</td>
                                        @endforeach
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="9" class="text-center"><h2>Данные отстутсвуют</h2></td>
                                    </tr>
                                @endforelse
                                </tbody>

                            </table>
                        @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/LabFive.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <div class="container">
                            <form action="{{route('CryptFive.crypting')}}" method="post">
                                {{csrf_field()}}
                                {{ method_field('POST') }}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Сообщение</label>
                                    <input type="text" class="form-control" name="mess" id="exampleInputEmail1"
                                           aria-describedby="emailHelp" placeholder="@if(isset($m_encrypted))@endif">
                                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with
                                        anyone else.</small>
                                </div>

                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>

                    </div>
                    @if(isset($m_encrypted))
                        <div class="container">
                            <div class="alert alert-success" role="alert">
                                Пользователь 1 ввёл сообщение : {{$messages}}
                            </div>
                            <div class="alert alert-success" role="alert">
                                Секретный ключ пользователя 1 : {{$sec_key_1}} <br>
                                Публичный ключ пользователя 1 : {{$pub_key}} <br>
                                Промежуточный ключ: {{$s_partial}} <br>
                                Финальный ключ: {{$s_full}} <br>
                                Зашифрованное сообщение : {{($m_encrypted)}}
                            </div>

                        </div>

                        <div class="container">
                            <div class="alert alert-danger" role="alert">
                                Пользователь 2 получил сообщение : {{$m_encrypted}}
                            </div>
                            <div class="alert alert-danger" role="alert">
                                Секретный ключ пользователя 2 : {{$sec_key_2}} <br>
                                Публичный ключ пользователя 2 : {{$pub_key2}} <br>
                                Промежуточный ключ: {{$m_partial}} <br>
                                Финальный ключ: {{$m_full}} <br>
                                Дешиф сообщение : {{$decrypt}}
                            </div>

                        </div>
                    @endif
                </div>

            </div>

        </div>

    </div>

@endsection

resources/views/LabOne.blade.php
@extends('layouts.app')

@section('content')
    @include('include.errors')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif


                        <form class="form-horizontal" action="{{route('CryptOne.crypt')}}" method="post">
                            {{csrf_field()}}
                            {{ method_field('POST') }}
                            {{--form include--}}
                            <div class="container">

                                <div class="row">
                                    <div class="col-sm">
                                        <label for="">Сообщение</label>
                                        <input class="form-control" type="text" placeholder="text"
                                               name="mess">
                                    </div>
                                    <div class="col-sm">
                                        <label for="">Ключ</label>
                                        <input class="form-control" type="text" name="key"
                                               placeholder="exaple@mail.ru">
                                    </div>
                                </div>
                                <hr/>

                                <hr/>

                                <div class="row myrow">

                                    <div class="col-sm pb-2" style="display: grid">
                                        <input class="btn btn-primary" name="action" type="submit" value="зашифровать">

                                    </div>

                                    <div class="col-sm pb-2" style="display: grid">
                                        <input class="btn btn-primary" name="action" type="submit" value="Decrypt">
                                    </div>
                                    <div class="col-sm pb-2" style="display: grid">
                                        <a href="{{route('CryptOne.index')}}"
                                           class="btn btn-primary mybutton">Отчистить</a>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="container">
                        @if(isset($messages) and isset($keys))
                            <div class="alert alert-primary" role="alert">
                                Сообщение: {{$messages}} <br>
                                Ключ: {{$keys}}
                            </div>

                            <div class="alert alert-danger" role="alert">
                                {{$text}} сообщение: @foreach($cryptArr as $arr){{$arr}}@endforeach
                            </div>


                        @endif
                    </div>

                </div>
                <form>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Example textarea</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1"
                                  rows="3">@include('include.Lab1')</textarea>
                    </div>
                </form>

                <div class="container">
                    @if(isset($test))
                    <div class="alert alert-success" role="alert">
                        Демонстрационный массив
                    </div>

                    <table class="table table-bordered table-hover">

                        <tbody>

                        @forelse($test as  $te => $t)
                            <tr>
                                @foreach($t as $tt)
                                    <td>{{$tt}}</td>
                                @endforeach
                            </tr>
                        @empty
                            <tr>
                                <td colspan="9" class="text-center"><h2>Данные отстутсвуют</h2></td>
                            </tr>
                        @endforelse
                        </tbody>

                    </table>
                    @endif
                        @if(isset($decode))
                            <div class="alert alert-info" role="alert">
                                A simple info alert—check it out!
                            </div>

                            <table class="table table-bordered table-hover">

                                <tbody>

                                @forelse($decode as $dec => $t)
                                    <tr>
                                        @foreach($t as $tt)
                                            <td>{{$tt}}</td>
                                        @endforeach
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="9" class="text-center"><h2>Данные отстутсвуют</h2></td>
                                    </tr>
                                @endforelse
                                </tbody>

                            </table>
                        @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/LabTree.blade.php
@extends('layouts.app')

@section('content')
    @include('include.errors')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif


                        <form class="form-horizontal" action="{{route('CryptTree.crypt.go')}}" method="post">
                            {{csrf_field()}}
                            {{ method_field('POST') }}
                            {{--form include--}}
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm">
                                        <label for="">Выберите язык</label>

                                    </div>
                                    <div class="col-sm">
                                        <div class="col-sm pb-2" style="display: grid">
                                            <a href="{{route('CryptTree.crypt.ru')}}"
                                               class="btn btn-primary mybutton">Русский</a>
                                        </div>
                                    <div class="col-sm pb-2" style="display: grid">
                                        <a href="{{route('CryptTree.crypt')}}"
                                           class="btn btn-primary mybutton">Ангийский</a>
                                    </div></div>
                                <div class="col-sm pb-2" style="display: grid">
                                    <a href="{{route('CryptTree.Vernam')}}"
                                       class="btn btn-primary mybutton">Vernam</a>
                                </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm">
                                        <label for="">Сообщение</label>
                                        <input class="form-control" type="text" placeholder="text"
                                               name="mess">
                                    </div>
                                    <div class="col-sm">
                                        <label for="">Ключ</label>
                                        <input class="form-control" type="text" name="key"
                                               placeholder="key">
                                    </div>
                                </div>
                                <hr/>

                                <hr/>

                                <div class="row myrow">

                                    <div class="col-sm pb-2" style="display: grid">
                                        <input class="btn btn-primary" name="action" type="submit" value="зашифровать">

                                    </div>

                                    <div class="col-sm pb-2" style="display: grid">
                                        <input class="btn btn-primary" name="action" type="submit" value="Decrypt">
                                    </div>
                                    <div class="col-sm pb-2" style="display: grid">
                                        <a href="{{route('CryptTree.crypt')}}"
                                           class="btn btn-primary mybutton">Отчистить</a>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>
                <div class="container">
                    @if(isset($cryptArr))

                        <div class="alert alert-danger" role="alert">
                            сообщение: {{implode('',$cryptArr) }}
                        </div>


                    @endif
                </div>

                </div>


            </div>
            @if(isset($messages))
            <table class="table table-bordered table-hover">

                <thead>
                <tr>
                    @foreach($messages as  $te)
                        <th scope="col">{{$te}}</th>
                    @endforeach
                </tr>
                </thead>
                <tbody>
                <tr>
                    @foreach($al_index as  $index)
                        <th scope="col">{{$index}}</th>
                    @endforeach
                </tr>
                <tr>
                    @foreach($Auto_key as  $Auto)
                        <th scope="col">{{$Auto}}</th>
                    @endforeach
                </tr>
                <tr>
                    @foreach($keykey as  $k)
                        <th scope="col">{{$k}}</th>
                    @endforeach
                </tr>
                <tr>
                    @foreach($crypt as  $index)
                        <th scope="col">{{$index}}</th>
                    @endforeach
                </tr>
                <tr>
                    @foreach($crypt_index as  $index)
                        <th scope="col">{{$index}}</th>
                    @endforeach
                </tr>
                <tr>

                </tr>
                </tbody>
            </table>
                @endif
           <img src="{{$img}}" class="img-fluid" alt="Responsive image">
        </div>
    </div>
    <br>

@endsection

resources/views/LabTwo.blade.php
@extends('layouts.app')

@section('content')
    @include('include.errors')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif


                        <form class="form-horizontal" action="{{route('CryptTwo.crypt')}}" method="post">
                            {{csrf_field()}}
                            {{ method_field('POST') }}
                            {{--form include--}}
                            <div class="container">

                                <div class="row">
                                    <div class="col-sm">
                                        <label for="">Сообщение</label>
                                        <input class="form-control" type="text" placeholder="text"
                                               name="mess">
                                    </div>
                                    <div class="col-sm">
                                        <label for="">Ключ</label>
                                        <input class="form-control" type="text" name="key"
                                               placeholder="key">
                                    </div>
                                </div>
                                <hr/>

                                <hr/>

                                <div class="row myrow">

                                    <div class="col-sm pb-2" style="display: grid">
                                        <input class="btn btn-primary" name="action" type="submit" value="зашифровать">

                                    </div>

                                    <div class="col-sm pb-2" style="display: grid">
                                        <input class="btn btn-primary" name="action" type="submit" value="Decrypt">
                                    </div>
                                    <div class="col-sm pb-2" style="display: grid">
                                        <a href="{{route('CryptTwo.index')}}"
                                           class="btn btn-primary mybutton">Отчистить</a>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="container">
                        @if(isset($messages) and isset($keys))
                            <div class="alert alert-primary" role="alert">
                                Сообщение: {{$messages}} <br>
                                Ключ: {{$keys}}
                            </div>

                            <div class="alert alert-danger" role="alert">
                                {{$text}} сообщение: {{$cryptArr }}
                            </div>


                        @endif
                    </div>

                </div>


            </div>

        </div>
    </div>
    <br>
    <div class="container">
        @if(isset($letter))
            <table class="table table-bordered table-hover">

                <thead>
                <tr>
                    @foreach(str_split(str_replace(' ', '' ,$messages)) as  $te)
                        <th scope="col">{{$te}}</th>
                    @endforeach
                </tr>
                </thead>
                <tbody>

                <tr>
                    @for($i = 0; $i < strlen(str_replace(' ', '' ,$messages)); $i++)
                        <td>{{$arr_key[$itter]}}</td>
                        <div class="btn" style="visibility: hidden">{{$itter += 1}}</div>
                        @if($itter >= strlen($keys))
                            <div class="btn" style="visibility: hidden">{{$itter = 0}}</div>
                        @endif


                    @endfor
                </tr>

                <tr>
                    @foreach(str_split(str_replace(' ', '' ,$cryptArr)) as  $te)
                        <th scope="col">{{$te}}</th>
                    @endforeach
                </tr>
                </tbody>
            </table>
        @endif

        <br>
        @if(isset($letter))
            <table class="table table-bordered table-hover">

                <thead>
                <tr>
                    @foreach($letter as  $te)
                        <th scope="col">{{$te}}</th>
                    @endforeach
                </tr>
                </thead>
                <tbody>

                @for($i = 0; $i < strtolower(strlen($keys)); $i++)
                    <tr>
                        @for($j = array_search(strtolower($keys[$i]), $letter); $j < strlen($string_letter); $j++)
                            <td>{{$letter[$j]}}</td>
                        @endfor
                        @for($q = 0; $q < array_search(strtolower($keys[$i]), $letter); $q++)
                            <td>{{$letter[$q]}}</td>
                        @endfor

                    </tr>
                @endfor

                </tbody>
            </table>
        @endif





    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                        <div class="container">
                            <div class="row">
                                <div class="col-sm">
                                    <table class="table">

                                        <tbody>
                                        <tr>
                                            <th scope="row"><a href="{{route('CryptOne.index')}}" class="btn btn-primary mybutton">Лаб 1</a></th>
                                            <th scope="row"><a href="{{route('CryptTwo.index')}}" class="btn btn-primary mybutton">Лаб 2</a></th>
                                            <th scope="row"><a href="{{route('CryptTree.crypt')}}" class="btn btn-primary mybutton">Лаб 3</a></th>
                                        </tr>
                                        <tr>
                                            <th scope="row"><a href="{{route('aes')}}" class="btn btn-primary mybutton">Лаб 4</a></th>
                                            <th scope="row"><a href="{{route('CryptFive')}}" class="btn btn-primary mybutton">Лаб 5</a></th>
                                            <th scope="row"><a href="{{route('rsa')}}" class="btn btn-primary mybutton">RSA</a></th>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection